# Generated by Django 4.1.5 on 2023-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_chatmessage_sender_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
