# Generated by Django 4.1.5 on 2023-01-28 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0003_rename_user_chatmessage_sender_chatroom_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorize_payment', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('card_number', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=5)),
                ('card_holder', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
