# Generated by Django 4.1.5 on 2023-01-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_group_message_remove_chatroom_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='purpose',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
