# Generated by Django 4.1.5 on 2023-02-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_group_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='purpose',
            field=models.CharField(default='', max_length=255),
        ),
    ]
