# Generated by Django 4.1.5 on 2023-02-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_group_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
