# Generated by Django 4.1.5 on 2023-02-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_message_chat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_type',
            new_name='type',
        ),
    ]
