# Generated by Django 4.1.5 on 2023-02-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_rename_chat_type_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(default='private', max_length=10),
        ),
    ]
