# Generated by Django 4.1.5 on 2023-02-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_alter_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
