# Generated by Django 4.1.4 on 2023-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='signup_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
