# Generated by Django 4.1.4 on 2023-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_loggedin',
            new_name='chat_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='news_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
