# Generated by Django 4.1.4 on 2023-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_signup_date_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_verify',
            field=models.BooleanField(default=False),
        ),
    ]
