# Generated by Django 4.1.4 on 2023-01-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_id_card_user_id_card_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_card_verify',
            new_name='id_card_verified',
        ),
    ]
