# Generated by Django 4.1.5 on 2023-01-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_id_card_verify_user_id_card_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
